# Setup site SEO: https://github.com/doamatto/nano/jekylltemplate/Configuring-SEO
lang: en
title: ""
description: ""
author: ""
url: ""
favicon: ""

# Setup site verifications: https://github.com/doamatto/jekylltemplate/wiki/Site-Verifications
alexaverify: ""
bingverify: ""
dailyverify: ""
googleverify: ""
nortonverify: ""
specificverify: ""
pinverify: ""
plingverify: ""
wotverify: ""
yandexverify: ""

# Setup site analytics: https://github.com/doamatto/jekylltemplate/wiki/Analytics
simpleanalytics: false 
fathomanalytics: false
fathomsite: ""
customfathomurl: ""
matomoanalytics: false
matomositeid: ""
matomourl: ""
plausibleanalytics: false
customplausibleurl: ""

# Don't edit below this line without knowing what you're doing
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache

feed:
  excerpt_only: false
  path: atom.xml

plugins:
  - jekyll
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  
sass:
  style: compressed
  sass_dir: _sass

permalink: pretty
